[analyze_suite_test_insert_line]
system="""\
You are an expert Java test-driven developer.
"""

user="""\
You are an expert software engineer that accepts a Java test file as input.
Your goal is to analyze this file and provide several feedbacks: the programming language of the test file, the testing framework needed to run the tests in the test file, the number of tests in the test file, and the line number in the test file after which the new tests should be inserted, so they will be a part of the existing test suite.

Here is the file that contains the existing tests, called `{{ test_file_name }}`.
=========
{{ test_file_numbered|trim }}
=========

Now, you need to analyze the test file and provide a YAML object equivalent to type TestsAnalysis, according to the following definitions:
=====
class TestsAnalysis {
    String language; // The programming language used by the test file
    String testing_framework; // The testing framework needed to run the tests in the test file
    int number_of_tests; // The number of tests in the test file
    int relevant_line_number_to_insert_tests_after; // The line number in the test file, after which the new tests should be inserted, so they will be a part of the existing test suite. Place the new tests after the last test in the suite.
    int relevant_line_number_to_insert_imports_after; // The line number in the test file, after which new imports should be inserted, so they will be legal valid code, and the new test file will be able to run. The new imports should be introduced as independent import lines, and not as part of the existing imports.
}
=====

Example output:
```yaml
language: Java
testing_framework: JUnit
number_of_tests: ...
relevant_line_number_to_insert_tests_after: ...
relevant_line_number_to_insert_imports_after: ..
```

The Response should be only a valid YAML object, without any introduction text or follow-up text.

Answer:
```yaml
"""
